id: PF7181558
initial_creation_type: input
source_metadata:
  Title: Antarvyāptisamarthanam
  Editor: '-'
  Publisher: Indian Council of Philosophical Research
  Place of Publication: New Delhi
  Year: '2002'
  अन्तर्व्याप्तिसमर्थनम्:
    Text Version: Devanagari
    Input Personnel: Rashmi Shakya
    Input Date: June, 2017
    Proof Reader: Rashmi Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:04:26.851900'
last_modified_at: '2022-03-08T17:04:26.851908'
